// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCALAMbDJmamr-UVW_zkSa4xEuoaxAZA',
    appId: '1:602810632462:android:beaa691facdf20accb2f5f',
    messagingSenderId: '602810632462',
    projectId: 'salon-8853a',
    storageBucket: 'salon-8853a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGR1DWfsz6TR8XyZj1EOPfu_dgZK_d4i0',
    appId: '1:602810632462:ios:b592a5e4a85a2d87cb2f5f',
    messagingSenderId: '602810632462',
    projectId: 'salon-8853a',
    storageBucket: 'salon-8853a.appspot.com',
    androidClientId: '602810632462-2rlkk3gasqlm7c31v3fv02se2gi7hu6n.apps.googleusercontent.com',
    iosClientId: '602810632462-tnd3mkisaar621k05ttefqdksjg8h9uh.apps.googleusercontent.com',
    iosBundleId: 'com.spiderte8.salon',
  );
}
